plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  DisabledByDefault: false
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "**/bin/*"
    - "**/config.ru"
    - "**/db/**/*"
    - "**/schema.rb"
    - "**/node_modules/**/*"
    - "**/vendor/**/*"
    - "**/vendor/**/*.txt"
    - "**/test/**/*"
    - "**/tmp/**/*"

# Dim down rubocop's annoyance level below:

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/LineLength:
  Exclude:
    - app/views/**/*.rb
    - app/components/**/*.rb
    - lib/generators/**/*.rb
  Max: 125

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/paperclip-vips.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - app/events/**/*.rb
    # - app/views/**/*.rb

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
